services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/backend:${GITHUB_SHA}"
    ports:
      - "5293:5293"

  frontend:
    build:
      context: ./pos_frontend
      dockerfile: Dockerfile
    image: "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/frontend:${GITHUB_SHA}"
    ports:
      - "3000:3000"
