name: 'Build and Deploy to Cloud Run'

on:
  workflow_dispatch:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: 'etaxth'          # แก้ให้ตรงกับ Google Cloud project ID ของคุณ
  REGION: 'asia-southeast1'     # แก้ให้ตรงกับ region ของคุณ
  SERVICE: 'trainee-jidapa'     # ชื่อ Cloud Run service

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # ----------------------------
      # 1) เพิ่ม token_format: 'access_token'
      # ----------------------------
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'

      # BEGIN - Docker auth and build
      # ----------------------------
      # 2) เปลี่ยน password: จาก auth_token เป็น access_token
      # ----------------------------
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        id: deploy
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'
      # END - Docker auth and build

      - name: 'Show output'
        run: |
          echo "Cloud Run URL: ${{ steps.deploy.outputs.url }}"
