name: 'Build and Deploy to Cloud Run (2 services with Docker Compose)'

on:
  # สั่งรัน workflow เมื่อมี push ไป branch main หรือกด manual
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: "etaxth"    # ใส่ Project ID ของ Google Cloud
  REGION: "asia-southeast1"              # Region ที่ใช้
  REPO_NAME: "trainee-jidapa"                    # ชื่อ repo ใน Artifact Registry (ปรับตามจริง)

  BACKEND_SERVICE: "jidapa-backend-service"   # ชื่อ Cloud Run Service ของฝั่ง backend
  FRONTEND_SERVICE: "jidapa-frontend-service" # ชื่อ Cloud Run Service ของฝั่ง frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Authenticate to Google Cloud
      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          # ใช้ json credentials หรือ Workload Identity
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'  # สำคัญ ถ้าจะใช้ docker login ต้องใช้ access_token

      # 2) Docker login ไปยัง Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # 3) Build & Push image สำหรับ 2 service ด้วย Docker Compose
      - name: 'Build and Push container images'
        run: |
          # ส่งตัวแปรเข้า docker compose แบบชั่วคราว
          export PROJECT_ID="${{ env.PROJECT_ID }}"
          export REGION="${{ env.REGION }}"
          export GITHUB_SHA="${{ github.sha }}"
          
          # สั่ง build + push ตามที่ระบุใน docker-compose.yml
          docker compose build
          docker compose push

      # 4) Deploy Backend service
      - name: 'Deploy to Cloud Run (Backend)'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        id: deploy_backend
        with:
          service: '${{ env.BACKEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:${{ github.sha }}'

      # 5) Deploy Frontend service
      - name: 'Deploy to Cloud Run (Frontend)'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        id: deploy_frontend
        with:
          service: '${{ env.FRONTEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:${{ github.sha }}'

      # 6) (Optional) Show outputs เช่น URLs ของแต่ละ service
      - name: 'Show output URLs'
        run: |
          echo "Backend URL: ${{ steps.deploy_backend.outputs.url }}"
          echo "Frontend URL: ${{ steps.deploy_frontend.outputs.url }}"
